GET http://localhost:3000/api/auth 
user_id: 19000001
password: test12345

###
POST http://localhost:3000/api/event 
AuthToken: ae5d75b0-2b2b-4aa5-bd87-87218ead20f5
Content-Type: application/json

{
    "title": "Second Day Extravaganza",
    "eventDate": "2023-08-22T00:00:00.000Z",
    "content": "Hello everyone! welcome to S.Y. 2023-2024",
    "photo_img_links": [
        "https://th.bing.com/th/id/OIP.qw2DwMX4cyYQAZNzaQmGlQHaIW?pid=ImgDet&rs=1"
    ]
}

###
GET http://localhost:3000/api/event 

###
PATCH  http://localhost:3000/api/event/64d4d36ad71b0cf0cfdc7a5f
AuthToken: ae5d75b0-2b2b-4aa5-bd87-87218ead20f5
Content-Type: application/json

{
    "title": "First Day Extravaganza",
    "content": "Hello everyone! welcome to S.Y. 2023-2024"
}

###
DELETE  http://localhost:3000/api/event/I
AuthToken: 4a1fba73-ff2b-498b-bf9d-bd3d6d3016f2