GET http://localhost:3000/api/auth 
user_id: 19000001
password: test12345

###

POST http://localhost:3000/api/order
AuthToken: 5891209e-105d-4d1a-8917-854316bb77ed
Content-Type: application/json

{
    "merch_id": "64d4e0e5aa0832371249a8da",
    "information": "I order again haha!",
    "size": "regular",
    "color": "N/A",
    "status": "ORDERED",
    "quantity": 2
}


###

GET http://localhost:3000/api/order/PSITS_73488738Y5016NVX
AuthToken: 5891209e-105d-4d1a-8917-854316bb77ed


###

GET http://localhost:3000/api/order
AuthToken: 5891209e-105d-4d1a-8917-854316bb77ed

###

PATCH http://localhost:3000/api/order/PSITS_73191111Y2726TDZ
AuthToken: cf08e8bc-1501-4a94-8d9f-15f4268cb085
Content-Type: application/json

{
    "status": "REVIEWED",
    "review": "Verry Good!",
    "rating": 5
}

###

DELETE http://localhost:3000/api/order/PSITS_16068431I3804GQV
AuthToken: 8e72e65f-9faf-4767-bb30-fdc50169ef98