import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ShoppingBag } from "lucide-react";
import Wrapper from "@/components/Wrapper";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useShoppingCart } from "@/components/Context";
const dummyData = [
    {
        id: 1,
        title: "Tiger",
        createdBy: 1234,
        information: "Cool T-shirt",
        price: 100,
        discount: 10,
        stock: 20,
        photo_img_link: "",
        size: "Large",
        color: "Black",
        rating: 20,
        quantity: 1,
        showPublic: true,
    },
    {
        id: 2,
        title: "Slant Hoodie",
        createdBy: 1234,
        information: "Cool T-shirt",
        price: 750,
        discount: 150,
        stock: 20,
        photo_img_link: "",
        size: "Large",
        color: "Black",
        rating: 20,
        quantity: 1,
        showPublic: true,
    },
    {
        id: 3,
        title: "Slant Hoodie",
        createdBy: 1234,
        information: "Cool T-shirt",
        price: 50,
        discount: 0,
        stock: 20,
        photo_img_link: "",
        size: "Large",
        color: "Black",
        rating: 20,
        quantity: 1,
        showPublic: true,
    },
    {
        id: 4,
        title: "Slant Hoodie",
        createdBy: 1234,
        information: "Cool T-shirt",
        price: 400,
        discount: 50,
        stock: 20,
        photo_img_link: "",
        size: "Large",
        color: "Black",
        rating: 20,
        quantity: 1,
        showPublic: true,
    },
    {
        id: 5,
        title: "Slant Hoodie",
        createdBy: 1234,
        information: "Cool T-shirt",
        price: 300,
        discount: 15,
        stock: 20,
        photo_img_link: "",
        size: "Large",
        color: "Black",
        rating: 20,
        quantity: 1,
        showPublic: true,
    },
    {
        id: 6,
        title: "Slant Hoodie",
        createdBy: 1234,
        information: "Cool T-shirt",
        price: 150,
        discount: 5,
        stock: 20,
        photo_img_link: "",
        size: "Large",
        color: "Black",
        rating: 20,
        quantity: 1,
        showPublic: true,
    },
];
const Merchandise = () => {
    const { addToCart } = useShoppingCart();
    return (_jsx(Wrapper, { title: "PSITS | Merchandise", children: _jsxs("div", { className: "min-h-screen my-20", children: [_jsx("h1", { className: "text-7xl text-center font-bold text-[#1A1A1A] mb-20", children: "Merchandise" }), _jsx("div", { className: "flex flex-row flex-wrap justify-center", children: dummyData.map((item) => (_jsxs(Card, { className: "w-[350px] border-0 shadow-none", children: [_jsxs(CardHeader, { className: "relative", children: [_jsx("div", { className: "w-full h-[400px] bg-gray-200 rounded-lg shadow-lg" }), _jsx(Button, { className: "bg-[#000] bg-opacity-100 hover:bg-[#000] hover:bg-opacity-75 py-[7.5%] absolute bottom-8 end-8 rounded-full", onClick: () => addToCart(item), children: _jsx(ShoppingBag, { size: 20 }) })] }), _jsx(CardContent, { children: _jsxs("div", { className: "flex flex-row justify-between", children: [_jsx("h1", { className: "text-lg font-semibold", children: item.title }), _jsxs("p", { className: "text-lg font-light", children: ["\u20B1", item.price, ".00"] })] }) })] }, item.id))) })] }) }));
};
export default Merchandise;
