import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Wrapper from "@/components/Wrapper";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Pencil } from "lucide-react";
import { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectTrigger, SelectValue, } from "@/components/ui/select";
const Profile = () => {
    return (_jsx(Wrapper, { title: "PSITS | Profile", noMargin: true, children: _jsxs("div", { className: "flex flex-col my-20 gap-y-10 mx-[30%]", children: [_jsx("div", { className: "flex justify-center", children: _jsx("span", { className: "font-bold text-2xl", children: "Edit Profile" }) }), _jsx("div", { className: "flex justify-center", children: _jsxs("div", { className: "bg-gray-200 h-[150px] w-[150px] rounded-full border-2 border-[#ccc] relative", children: [_jsx(Label, { htmlFor: "img", children: _jsx(Pencil, { className: "bg-[#268EA7] hover:bg-[#3da7c2] w-[40px] h-[40px] rounded-full absolute bottom-0 end-0 border-2 border-white p-2", color: "#fff" }) }), _jsx(Input, { type: "file", className: "hidden", id: "img" })] }) }), _jsxs("div", { className: "grid grid-cols-2 gap-y-10 gap-x-5 mt-10", children: [_jsxs("div", { className: "flex flex-col gap-y-3", children: [_jsx(Label, { className: "text-gray-500", children: "First Name" }), _jsx(Input, { autoComplete: "off", id: "firstname", placeholder: "Enter your firstname", className: "w-full" })] }), _jsxs("div", { className: "flex flex-col gap-y-3", children: [_jsx(Label, { className: "text-gray-500", children: "Last Name" }), _jsx(Input, { autoComplete: "off", id: "lastname", placeholder: "Enter your lastname" })] }), _jsxs("div", { className: "col-span-2 flex flex-col gap-y-3", children: [_jsx(Label, { className: "text-gray-500", children: "E-mail" }), _jsx(Input, { autoComplete: "off", id: "email", placeholder: "Enter your e-mail" })] }), _jsxs("div", { className: "col-span-2 flex flex-col gap-y-3", children: [_jsx(Label, { className: "text-gray-500", children: "Password" }), _jsx(Input, { autoComplete: "off", id: "email", placeholder: "Enter a new password" })] }), _jsxs("div", { children: [_jsx(Label, { className: "text-gray-500", children: "Course" }), _jsxs(Select, { children: [_jsx(SelectTrigger, { className: "w-full", children: _jsx(SelectValue, { placeholder: "Select Course" }) }), _jsx(SelectContent, { children: _jsxs(SelectGroup, { children: [_jsx(SelectLabel, { children: "Course" }), _jsx(SelectItem, { value: "bsit", children: "BSIT" }), _jsx(SelectItem, { value: "bscs", children: "BSCS" })] }) })] })] }), _jsxs("div", { children: [_jsx(Label, { className: "text-gray-500", children: "Year" }), _jsxs(Select, { children: [_jsx(SelectTrigger, { className: "w-full", children: _jsx(SelectValue, { placeholder: "Select Year" }) }), _jsx(SelectContent, { children: _jsxs(SelectGroup, { children: [_jsx(SelectLabel, { children: "Year" }), _jsx(SelectItem, { value: "1", children: "1" }), _jsx(SelectItem, { value: "2", children: "2" }), _jsx(SelectItem, { value: "3", children: "3" }), _jsx(SelectItem, { value: "4", children: "4" })] }) })] })] })] }), _jsx(Button, { type: "submit", className: "bg-[#268EA7] hover:bg-[#3da7c2] w-[200px]", children: "Save Changes" })] }) }));
};
export default Profile;
